### ISSUE TITLE
Update to ES6? 

### ISSUE THREAD

**Issue by MiriamPeskowitz** [learn-co-curriculum/react-updating-state#10]
Or, we could do this using the proposed object spread operator in the next version of JS: RECOMMENDED

-- this should be updated, with more info/link to spread operator.

**Comment by maxwellbenton** [comment]
Hi @MiriamPeskowitz,

Thank you for spotting this and providing feedback. We've added an extra paragraph to explain how the spread operator works here and are in the process of introducing this syntax earlier on in JavaScript as well.

Thank you for all your contributions to the learn.co curriculum!

**Comment by MiriamPeskowitz** [comment]
That’s great; loving the spread operator! 

On Dec 19, 2018, at 2:23 PM, Maxwell Benton <notifications@github.com> wrote:

Hi @MiriamPeskowitz <https://github.com/MiriamPeskowitz>,

Thank you for spotting this and providing feedback. We've added an extra paragraph to explain how the spread operator works here and are in the process of introducing this syntax earlier on in JavaScript as well.

Thank you for all your contributions to the learn.co curriculum!
