### ISSUE TITLE
Compile Error, Webpack Incompatibility 

### ISSUE THREAD

**Issue by mekowalski** [learn-co-curriculum/react-updating-state#11]
Hello!  I'm reaching on on regards to a compiling error received for this code-along lesson.  Before writing any code I ran `npm install && npm start` as the lesson provides.  Upon that, I received a `Failed to compile` error in both the browser and the console.

Fortunately I was able to find a solution provided by Dan Abramov(the co-creator of React).  His states that Webpack is not compatible with `create-react-app` projects.  I don't know if I should assume this but the lessons code-along project may have been created via `create-react-app` and then the addition of Webpack was made.

I followed along with Dan's solution and at the very end of his solution ran `npm install && npm start` which successfully delivered the browser for the lesson's code-along.  I will include the link to his solution.  I did alter my forked copy of the lesson's repository and made the changes on my copy only.  I also did this with a technical coach on zoom and we ran through the solution together to see what would happen.

I included the error and the before and after of `package.json`.  Along with the link to the solution.

Happy coding
Malind

[Dan Abramov's Solution](https://github.com/facebook/create-react-app/issues/2352#issuecomment-357363302)

![packagejsonbefore](https://user-images.githubusercontent.com/15252624/50366620-fef01d80-0537-11e9-97a6-b60e7d7a0ef7.png)
![packagejsonafter](https://user-images.githubusercontent.com/15252624/50366615-f861a600-0537-11e9-96f6-2bb8dbee8af3.png)
![compileerror](https://user-images.githubusercontent.com/15252624/50366635-0fa09380-0538-11e9-83aa-801e9bd94f01.png)

**Comment by maxwellbenton** [comment]
Hi @mekowalski,

Thank you for providing this feedback and your solution. Webpack has been removed from `package.json` so this should not occur for any future students.
