### ISSUE TITLE
Grammar issue 

### ISSUE THREAD

**Issue by TimeSmash** [learn-co-curriculum/react-updating-state#14]
This sentence: _See what happened there? It merged the state, but any objects get overwritten, because it doesn't deeply merge the state with the object you pass into this.setState()._ 
Corrected: See what happened there? It merged the state, but any **other** objects get overwritten, because it doesn't deeply merge the state with the object you pass into this.setState().

**Comment by maxwellbenton** [comment]
Hi @TimeSmash,

Thank you for spotting this. We've updated this lesson and fixed this sentence's structure, which should resolve this issue.

Thank you for contributing!
