### ISSUE TITLE
THIS SCHOOL IS THE BEST AT BEING UNDERSTAFFED

### ISSUE THREAD

**Issue by paurosero** [learn-co-curriculum/react-updating-state#20]
I CANNOT BELIEVE THIS SCHOOL IS SO UNDERSTAFFED. IT IS WORST THAN THE ACTUAL GOVERNMENT IN THIS CRISIS. I HATE THIS PRESIDENT AND THIS ADMINISTRATION BUT I HATE THIS SCHOOL MORE BECAUSE IT DOESNT DO WHATS BEST FOR THE STUDENTS BUT INSTEAD WHATS BEST FOR YOUR POCKETS. HAVE MORE PEOPLE ANSWERING QUESTIONS IN ASK A QUESTION

**Comment by cernanb** [comment]
Hello @paurosero, our students are our top priority and we are sorry to hear that you have experienced anything less than an amazing educational experience.  A member of our student services team will connect with you to better understand your concerns and how best we might resolve them.  Thank you for bringing your concerns to our attention.
