### ISSUE TITLE
you guys are the worst at  this

### ISSUE THREAD

**Issue by paurosero** [learn-co-curriculum/react-updating-state#21]
you should loose your teaching license since you can't teach at all. all you do is show people how to google since you are not teachers

**Comment by cernanb** [comment]
Hello @paurosero, our goal is to provide our students with the very best educational experience. We are concerned to hear that your experience has not met that expectation.  A member of our student services team will connect with you to better understand your concerns and how best we might resolve them.  Thank you for bringing your concerns to our attention.
