### ISSUE TITLE
Not a lab

### ISSUE THREAD

**Issue by jdbean** [learn-co-curriculum/react-updating-state#7]
This "lab" appears not be a lab but a readme. It is configured to act as a lab however. It would probably be better to modify this behavior

**Comment by maxwellbenton** [comment]
Thank you for spotting this and providing feedback.

We have updated the materials and converted this to a code along to utilize the provided react files and folders. 

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙

**Comment by arye-dov-eidelman** [comment]
This is still a lab in the online software engineering structured curriculum. 

![Screenshot from 2019-08-01 12-03-21](https://user-images.githubusercontent.com/7709411/62308949-7550e880-b454-11e9-8add-91554e769ef6.png)

**Comment by arye-dov-eidelman** [comment]
This is still an issue
